name: tests

on:
  push:
    branches:
      - dev

jobs:

  tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run tests
        run: mvn --batch-mode --update-snapshots verify
